__version__ = "0.0.1"
__author__ = "Adrian Price-Whelan"
__copyright__ = "2018 Adrian Price-Whelan"
__credits__ = ["Adrian Price-Whelan","Alexandar P. Mechev", "Julia Melo Rodrigues de Aguiar", "Leon Trapman"]
__license__ = "MIT"
__maintainer__ = "Adrian Price-Whelan"
__email__ = "adrn@astro.princeton.edu"
__status__ = "Planning"
__date__ = "2018-08-07"
